"""all-screenings expansion: nullable event_type, specialness, venue kind

Every screening is now stored, not only special ones (see
``docs/decisions/0008-drop-allocine-width-source.md`` and
``docs/coverage-matrix.md``). ``event_type`` becomes nullable (``None`` for
an ordinary screening); ``is_special``/``specialness_reasons``/
``specialness_confidence`` separate "worth surfacing" from "which special
category". Existing rows predate this split and were all inserted while
``event_type`` was NOT NULL, so every one of them is special by
construction — the ``is_special`` backfill default of ``1`` is exact, not
an approximation.

``venue.kind`` is backfilled from the venue name using a frozen snapshot of
``core/venues.classify_venue_kind``'s rules at the time of this migration
(deliberately not imported from the application module, which is free to
evolve independently of this historical snapshot).

Revision ID: 0edf9c163929
Revises: 85f0b217098d
Create Date: 2026-07-13 18:41:20.731626

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0edf9c163929"
down_revision: str | Sequence[str] | None = "85f0b217098d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Frozen snapshot of core/venues.py's institution list and chain prefixes,
# for the one-time backfill below — see the module docstring above.
_INSTITUTION_NAMES = (
    "La Cinémathèque française",
    "La Cinémathèque française - Salle Georges Franju",
    "La Cinémathèque française - Salle Henri Langlois",
    "Le Forum des images",
    "Fondation Jérôme Seydoux-Pathé",
    "Cinéma en plein air de La Villette",
)
_CHAIN_PREFIXES = (
    ("UGC%", "CHAIN_UGC"),
    ("Pathé%", "CHAIN_PATHE"),
    ("MK2%", "CHAIN_MK2"),
    ("CGR%", "CHAIN_OTHER"),
)


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("screeningevent", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_special", sa.Boolean(), nullable=False, server_default=sa.text("1")
            )
        )
        batch_op.add_column(sa.Column("specialness_reasons", sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("specialness_confidence", sa.Float(), nullable=True)
        )
        batch_op.alter_column(
            "event_type", existing_type=sa.VARCHAR(length=14), nullable=True
        )
        batch_op.create_index(
            batch_op.f("ix_screeningevent_is_special"), ["is_special"], unique=False
        )

    _venue_kind_enum = sa.Enum(
        "INSTITUTION",
        "CHAIN_UGC",
        "CHAIN_PATHE",
        "CHAIN_MK2",
        "CHAIN_OTHER",
        "INDEPENDENT",
        name="venuekind",
    )
    with op.batch_alter_table("venue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "kind", _venue_kind_enum, nullable=False, server_default="INDEPENDENT"
            )
        )

    _backfill_venue_kind()


def _backfill_venue_kind() -> None:
    """Reclassify existing venues beyond the 'INDEPENDENT' column default."""
    venue = sa.table(
        "venue", sa.column("name", sa.String), sa.column("kind", sa.String)
    )
    bind = op.get_bind()
    for name in _INSTITUTION_NAMES:
        bind.execute(
            venue.update().where(venue.c.name == name).values(kind="INSTITUTION")
        )
    for pattern, kind in _CHAIN_PREFIXES:
        bind.execute(venue.update().where(venue.c.name.like(pattern)).values(kind=kind))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("venue", schema=None) as batch_op:
        batch_op.drop_column("kind")

    with op.batch_alter_table("screeningevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_screeningevent_is_special"))
        batch_op.alter_column(
            "event_type", existing_type=sa.VARCHAR(length=14), nullable=False
        )
        batch_op.drop_column("specialness_confidence")
        batch_op.drop_column("specialness_reasons")
        batch_op.drop_column("is_special")

    # ### end Alembic commands ###
