"""initial schema

Revision ID: 85f0b217098d
Revises:
Create Date: 2026-07-06 22:50:18.805734

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

import cine_event_bot.core.models

# revision identifiers, used by Alembic.
revision: str = "85f0b217098d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "film",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("original_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("director", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("genres", sa.JSON(), nullable=True),
        sa.Column("overview", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("poster_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("vote_average", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id"),
    )
    op.create_index(op.f("ix_film_title_key"), "film", ["title_key"], unique=True)
    op.create_table(
        "subscriber",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column(
            "subscribed_at",
            cine_event_bot.core.models.UtcDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "venue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_venue_slug"), "venue", ["slug"], unique=True)
    op.create_table(
        "screeningevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dedup_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "AVANT_PREMIERE",
                "CINE_CONCERT",
                "RETROSPECTIVE",
                "OPEN_AIR",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "starts_at",
            cine_event_bot.core.models.UtcDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("has_team_present", sa.Boolean(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cycle_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("booking_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["film.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screeningevent_dedup_key"),
        "screeningevent",
        ["dedup_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_screeningevent_film_id"), "screeningevent", ["film_id"], unique=False
    )
    op.create_index(
        op.f("ix_screeningevent_venue_id"), "screeningevent", ["venue_id"], unique=False
    )
    op.create_table(
        "eventsighting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "PREMIERE_PROJO", "CINEMATHEQUE", "FORUM_DES_IMAGES", name="source"
            ),
            nullable=False,
        ),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "scraped_at",
            cine_event_bot.core.models.UtcDateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["screeningevent.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "source"),
    )
    op.create_index(
        op.f("ix_eventsighting_event_id"), "eventsighting", ["event_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_eventsighting_event_id"), table_name="eventsighting")
    op.drop_table("eventsighting")
    op.drop_index(op.f("ix_screeningevent_venue_id"), table_name="screeningevent")
    op.drop_index(op.f("ix_screeningevent_film_id"), table_name="screeningevent")
    op.drop_index(op.f("ix_screeningevent_dedup_key"), table_name="screeningevent")
    op.drop_table("screeningevent")
    op.drop_index(op.f("ix_venue_slug"), table_name="venue")
    op.drop_table("venue")
    op.drop_table("subscriber")
    op.drop_index(op.f("ix_film_title_key"), table_name="film")
    op.drop_table("film")
    # ### end Alembic commands ###
